export enum RequirementType {
    FUNCTIONAL = "FUNCIONAL",
    NON_FUNCTIONAL = "NO FUNCIONAL",
}

export enum RequirementStatus {
    PENDING = "PENDIENTE",
    REJECTED = "RECHAZADO",
    APPROVED = "APROBADO",
    IN_PROGRESS = "EN CONSTRUCCION",
    FINISHED = "TERMINADO",
    OBSOLETE = "OBSOLETO",
}

export enum RequirementVerificationMethod {
    INSPECTION = "INSPECCION",
    ANALYSIS = "ANALISIS",
    TEST = "PRUEBA",
    DEMONSTRATION = "DEMOSTRACION",
}

export enum RequirementCategory {
    FUNCTIONAL_SUITABILITY = "ADECUACION_FUNCIONAL",
    PERFORMANCE_EFFICIENCY = "EFICIENCIA_DESEMPENO",
    COMPATIBILITY = "COMPATIBILIDAD",
    USABILITY = "USABILIDAD",
    RELIABILITY = "FIABILIDAD",
    SECURITY = "SEGURIDAD",
    MAINTAINABILITY = "MANTENIBILIDAD",
    PORTABILITY = "PORTABILIDAD",
}

export enum RequirementRisk {
    LOW = "BAJO",
    MEDIUM = "MEDIO",
    HIGH = "ALTO",
    CRITICAL = "CRITICO",
}

export enum RequirementSource {
  BUSINESS_NEEDS = "NECESIDADES DEL NEGOCIO",
  SYSTEM_OBJECTIVES = "OBJETIVOS DEL SISTEMA",
  STAKEHOLDER_REQUESTS = "SOLICITUD DEL STAKEHOLDER",
  USE_CASES = "CASOS DE USO",
  MISUSE_CASES = "CASOS DE ABUSO",
  EXTERNAL_REGULATIONS = "NORMAS EXTERNAS",
}
